-- FASE 4 — Migración y sincronización D1 -> PostgreSQL
--
-- 1) Columnas "updated_at" espejo de las añadidas en D1 por
--    worker/migracion_fase4_sync_tracking.sql (users, results, sessions,
--    edit_requests, comments, club_info_solicitudes). El sincronizador las
--    usa para saber qué filas re-copiar en cada pasada incremental.
--
-- 2) sync_deletions: D1 borra filas físicamente (DELETE). PostgreSQL, al
--    ser una réplica separada, no se entera de esos DELETE por sí solo.
--    Como D1 no tiene (todavía) una tabla de auditoría de borrados
--    genérica, el sincronizador incremental compara IDs presentes en D1
--    contra los presentes en PostgreSQL en cada pasada para detectar
--    huecos y aplicar el DELETE también en PostgreSQL (ver
--    worker-secondary/sync/incremental.mjs). Esta tabla registra esos
--    borrados replicados, a efectos de auditoría/depuración.
--
-- 3) sync_state: estado/log de cada ejecución del sincronizador (ver
--    CRITERIO 12 de FASE4.md): última sincronización, resultado, nº de
--    registros, errores, duración.
BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE results ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE edit_requests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE club_info_solicitudes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS sync_deletions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name TEXT NOT NULL,
  record_id TEXT NOT NULL,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  run_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_sync_deletions_table ON sync_deletions(table_name);

CREATE TABLE IF NOT EXISTS sync_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'running', -- running, ok, error
  mode TEXT NOT NULL,                     -- 'initial' o 'incremental'
  records_processed INTEGER NOT NULL DEFAULT 0,
  records_inserted INTEGER NOT NULL DEFAULT 0,
  records_updated INTEGER NOT NULL DEFAULT 0,
  records_deleted INTEGER NOT NULL DEFAULT 0,
  errors INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER,
  detail TEXT -- JSON con detalle por tabla y errores, ver sync/state.mjs
);
CREATE INDEX IF NOT EXISTS idx_sync_state_started ON sync_state(started_at DESC);

-- Cursor por tabla: último valor de updated_at/created_at ya sincronizado.
-- Permite reanudar sin releer todo desde el principio si el proceso se
-- reinicia entre tablas.
CREATE TABLE IF NOT EXISTS sync_cursor (
  table_name TEXT PRIMARY KEY,
  last_synced_at TEXT,     -- valor TEXT tal cual viene de D1 (ISO datetime)
  last_synced_id INTEGER,  -- desempate para filas con el mismo timestamp
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
