-- Espejo en PostgreSQL de worker/migracion_origin_write_id.sql (y de la
-- copia en worker-secondary/migracion_origin_write_id.sql, aplicada sobre
-- D1). Ver ese archivo para el contexto completo: esta columna es la clave
-- de deduplicación que usa sync/incremental.mjs para reconciliar, en vez
-- de duplicar, una fila creada en PostgreSQL durante un failover cuando
-- D1 termina reproduciendo la escritura pendiente correspondiente.
BEGIN;

ALTER TABLE articles ADD COLUMN IF NOT EXISTS origin_write_id UUID;
ALTER TABLE results ADD COLUMN IF NOT EXISTS origin_write_id UUID;

-- Registro de conflictos que la reconciliación por origin_write_id no pudo
-- resolver automáticamente (ver reconciliarFilasPorOriginWriteId en
-- sync/pg-writer.mjs): casos en los que existía una fila huérfana de un
-- failover con el mismo origin_write_id que una fila nueva de D1, pero el
-- DELETE de la huérfana falló (típicamente por una FK de otra tabla
-- apuntando todavía a su id antiguo). Se registran aquí en vez de fallar
-- la sincronización entera, para revisión manual -- nunca se descartan en
-- silencio.
CREATE TABLE IF NOT EXISTS sync_write_id_conflicts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name TEXT NOT NULL,
  origin_write_id UUID NOT NULL,
  pk_huerfana JSONB NOT NULL,
  pk_d1 JSONB NOT NULL,
  error_message TEXT,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resuelto BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_sync_write_id_conflicts_pendientes
  ON sync_write_id_conflicts(resuelto) WHERE resuelto = FALSE;

COMMIT;
