-- Migración 009: tablas newsletter_suscriptores y newsletter_envios
-- (mismo esquema que worker/migracion_newsletter.sql en D1, aplicada aquí
-- a Postgres para que el esquema de ambas bases coincida).
--
-- Corrige el bug del botón "Eliminar" en el panel de Newsletter: la tabla
-- no existía en Postgres y no estaba en sync/tables.mjs, así que si una
-- petición del panel caía en el worker secundario (failover), leía datos
-- desincronizados del primario (D1) o fallaba directamente por falta de
-- tabla. Se añade aquí y se registra en sync/tables.mjs con
-- deleteDetection para que las bajas del panel de admin (DELETE, ver
-- worker/src/index.js) se repliquen también en Postgres.

BEGIN;

CREATE TABLE IF NOT EXISTS newsletter_suscriptores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  -- Token propio de este suscriptor para darse de baja con un enlace sin
  -- necesidad de iniciar sesión (va en cada boletín enviado).
  baja_token TEXT NOT NULL,
  activo INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  baja_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_newsletter_email ON newsletter_suscriptores(email);

-- Registro del último boletín semanal enviado, para que el disparador
-- programado (cron) sepa si ya tocó esta semana sin tener que llevar
-- cuenta aparte. Solo hay una fila, con id fijo = 1.
CREATE TABLE IF NOT EXISTS newsletter_envios (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  ultimo_envio_at TEXT
);
INSERT INTO newsletter_envios (id, ultimo_envio_at)
VALUES (1, NULL)
ON CONFLICT (id) DO NOTHING;

COMMIT;
