-- Migración 010: columnas de relleno automático en "results"
-- (mismo esquema que worker/migracion_relleno_automatico.sql en D1,
-- aplicada aquí a Postgres para que el esquema de ambas bases coincida).
--
-- Corrige el fallo del sincronizador D1 -> Postgres: la migración
-- original de D1 (worker/migracion_relleno_automatico.sql) añadió
-- "fuente" y "external_id" a "results" pero nunca se replicó en
-- Postgres. Desde entonces, sync/incremental.mjs detecta esas dos
-- columnas como "sin equivalente en PG" y corta la sincronización de
-- "results" en cada pasada (ver sync/incremental.mjs, comprobación de
-- columnasUtilizables/faltanEnPG). Como articles, match_events,
-- alineaciones, article_slug_redirects y comments dependen de results
-- por FK (ver DEPENDENCIAS_FK en sync/tables.mjs), también se saltaban
-- en cascada en cada pasada.

BEGIN;

ALTER TABLE results ADD COLUMN IF NOT EXISTS fuente TEXT NOT NULL DEFAULT 'redaccion';
ALTER TABLE results ADD COLUMN IF NOT EXISTS external_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_results_external_id
  ON results(external_id) WHERE external_id IS NOT NULL;

-- Mismas tablas auxiliares que crea la migración de D1, para que un
-- failover a la secundaria durante el relleno automático no falle por
-- falta de tabla (equipo_alias_externo, sync_partidos_auto).
CREATE TABLE IF NOT EXISTS equipo_alias_externo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_externo TEXT NOT NULL UNIQUE,
  nombre_interno TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS sync_partidos_auto (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  ultimo_sync_at TEXT,
  ultimo_sync_ok INTEGER NOT NULL DEFAULT 1,
  ultimo_error TEXT
);
INSERT INTO sync_partidos_auto (id, ultimo_sync_at)
VALUES (1, NULL)
ON CONFLICT (id) DO NOTHING;

COMMIT;
