-- Migración 011: cuentas de lectores + votos/denuncias de comentarios
-- (mismo esquema que worker/migracion_readers.sql y
-- worker/migracion_votos_denuncias_comentarios.sql en D1, aplicada aquí
-- a Postgres para que el esquema de ambas bases coincida).
--
-- Corrige el mismo tipo de fallo que la migración 010: sync/incremental.mjs
-- detectaba en "comments" las columnas "likes, dislikes, denuncias,
-- oculto_por_denuncia, reader_id" como "sin equivalente en PG" y cortaba
-- su sincronización en cada pasada. Además, la tabla "readers" (cuentas
-- de lectores) y sus tablas relacionadas (reader_sessions, comment_votes,
-- comment_reports) no existían en absoluto en Postgres: si una petición
-- de lectores (login, comentar, votar, denunciar) caía en el worker
-- secundario durante un failover, no tenía dónde escribir/leer.
--
-- Orden: readers primero (no depende de nadie), luego reader_sessions y
-- las columnas/índices de comments que referencian readers(id), y por
-- último comment_votes/comment_reports (dependen de comments).

BEGIN;

CREATE TABLE IF NOT EXISTS readers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  email_verificado INTEGER NOT NULL DEFAULT 0,
  verificacion_token TEXT,
  verificacion_token_expira TEXT,
  reset_token TEXT,
  reset_token_expira TEXT,
  activo INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_readers_email ON readers(email);

CREATE TABLE IF NOT EXISTS reader_sessions (
  id TEXT PRIMARY KEY,
  reader_id INTEGER NOT NULL REFERENCES readers(id),
  user_agent TEXT,
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  last_seen_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  revoked_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_reader_sessions_reader ON reader_sessions(reader_id);

ALTER TABLE comments ADD COLUMN IF NOT EXISTS reader_id INTEGER REFERENCES readers(id);
CREATE INDEX IF NOT EXISTS idx_comments_reader ON comments(reader_id);

ALTER TABLE comments ADD COLUMN IF NOT EXISTS likes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS dislikes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS denuncias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN IF NOT EXISTS oculto_por_denuncia INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS comment_votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id INTEGER NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  votante_id TEXT NOT NULL,
  valor INTEGER NOT NULL CHECK (valor IN (1, -1)),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE (comment_id, votante_id)
);
CREATE INDEX IF NOT EXISTS idx_comment_votes_comment ON comment_votes(comment_id);

CREATE TABLE IF NOT EXISTS comment_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id INTEGER NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  denunciante_id TEXT NOT NULL,
  motivo TEXT,
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  revisado INTEGER NOT NULL DEFAULT 0,
  UNIQUE (comment_id, denunciante_id)
);
CREATE INDEX IF NOT EXISTS idx_comment_reports_comment ON comment_reports(comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_reports_revisado ON comment_reports(revisado, created_at);

COMMIT;
