-- Migración 012: encuestas para lectores (polls / poll_options / poll_votes).
--
-- Mismo esquema que worker/migracion_encuestas.sql en D1, aplicado aquí a
-- Postgres para que el esquema de ambas bases coincida.
--
-- Causa raíz del incidente: la tabla "polls" existía en D1 (esquema
-- principal) pero nunca se había creado en Postgres (Railway). Cuando el
-- primario D1 fallaba y el sistema intentaba hacer failover a Railway,
-- /api/polls/portada también fallaba ahí con
-- `relation "polls" does not exist`, porque la tabla directamente no
-- existía en Postgres. Railway no podía absorber ese tráfico durante el
-- failover.
--
-- Orden: polls primero (depende de articles y users, que ya existen),
-- luego poll_options (depende de polls), y por último poll_votes
-- (depende de polls, poll_options y readers).

BEGIN;

CREATE TABLE IF NOT EXISTS polls (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pregunta TEXT NOT NULL,
  article_id INTEGER REFERENCES articles(id) ON DELETE SET NULL,
  en_portada INTEGER NOT NULL DEFAULT 0,
  orden_portada INTEGER NOT NULL DEFAULT 0,
  estado TEXT NOT NULL DEFAULT 'abierta',
  cierra_en TEXT,
  autor_id INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
CREATE INDEX IF NOT EXISTS idx_polls_article ON polls(article_id);
CREATE INDEX IF NOT EXISTS idx_polls_portada ON polls(en_portada, orden_portada);
CREATE INDEX IF NOT EXISTS idx_polls_estado ON polls(estado);

CREATE TABLE IF NOT EXISTS poll_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INTEGER NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  texto TEXT NOT NULL,
  orden INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_poll_options_poll ON poll_options(poll_id);

CREATE TABLE IF NOT EXISTS poll_votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INTEGER NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  option_id INTEGER NOT NULL REFERENCES poll_options(id) ON DELETE CASCADE,
  reader_id INTEGER NOT NULL REFERENCES readers(id),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE (poll_id, reader_id)
);
CREATE INDEX IF NOT EXISTS idx_poll_votes_poll ON poll_votes(poll_id);
CREATE INDEX IF NOT EXISTS idx_poll_votes_option ON poll_votes(option_id);

COMMIT;
