-- Migración 014: tienda de acreditación (tienda_productos / tienda_pedidos).
--
-- Mismo esquema que worker/migracion_tienda.sql en D1, portado a Postgres.
--
-- Causa raíz: igual que con "polls" (ver migración 012), esta tabla
-- existía en D1 pero nunca se había creado en Postgres. Al primario D1
-- fallar y hacer failover, cualquier ruta de la tienda fallaba en
-- Railway con `relation "tienda_pedidos" does not exist`.
--
-- Nota: había un worker-secondary/migracion_tienda.sql suelto (copia
-- textual del de D1, en sintaxis SQLite) que nunca llegó a aplicarse
-- porque no vivía en db/migrations/ -- el runner (scripts/migrate.mjs)
-- solo lee esa carpeta. Esta migración es la versión Postgres real de
-- ese archivo.
--
-- No se incluye el seed del catálogo (los 5 productos de ejemplo): eso
-- ya se sincroniza desde D1 vía sync/tables.mjs una vez la tabla existe
-- aquí, así que insertarlo también a mano aquí duplicaría filas.

BEGIN;

CREATE TABLE IF NOT EXISTS tienda_productos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio_centimos INTEGER NOT NULL,
  imagen_url TEXT,
  variantes TEXT,
  requiere_para_acreditacion INTEGER NOT NULL DEFAULT 0,
  activo INTEGER NOT NULL DEFAULT 1,
  orden INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS tienda_pedidos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES users(id),
  producto_id INTEGER NOT NULL REFERENCES tienda_productos(id),
  producto_nombre TEXT NOT NULL,
  variante TEXT,
  precio_centimos INTEGER NOT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente_pago',
  referencia_pago TEXT,
  nota_gestion TEXT,
  gestionado_por INTEGER REFERENCES users(id),
  gestionado_en TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE INDEX IF NOT EXISTS idx_tienda_pedidos_usuario ON tienda_pedidos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_tienda_pedidos_estado ON tienda_pedidos(estado);

-- Ya puede existir si otra migración anterior la añadió; IF NOT EXISTS
-- por seguridad (Postgres sí soporta esta forma, a diferencia de SQLite).
ALTER TABLE users ADD COLUMN IF NOT EXISTS puede_gestionar_tienda INTEGER NOT NULL DEFAULT 0;

COMMIT;
