-- Migración 021: tabla "porras" (predicciones/ranking de lectores) +
-- columna "categorias_fijas" en "users".
--
-- Dos faltantes distintos encontrados al auditar el esquema de Postgres
-- contra D1 completo, agrupados aquí por ser pequeños y no depender uno
-- del otro:
--
-- 1) "porras": igual que pasó antes con "tienda" (ver migración 014) y
--    "polls" (ver migración 012), esta tabla existe en D1
--    (worker/migracion_porras.sql) y su Worker principal expone
--    /api/porras, /api/porras/resumen y /api/porras/ranking sobre ella,
--    pero nunca se creó en Postgres ni se registró en
--    sync/tables.mjs. A diferencia de tienda/polls, aquí el fallo ante
--    un failover a Railway sería total: worker-secondary/src/index.js
--    ni siquiera tiene implementadas esas rutas todavía, así que hoy
--    "porras" queda fuera del path de failover por completo (no hay
--    endpoint que falle con "relation does not exist", simplemente el
--    lector no puede hacer su porra mientras Railway esté activo). Se
--    crea aquí el esquema para cuando se porten también las rutas, y
--    para que sync/tables.mjs (edición manual aparte, ver nota al
--    final) pueda empezar a replicar los datos ya existentes en D1.
--
-- 2) "categorias_fijas" en "users": columna real en D1
--    (worker/migracion_categorias_fijas_redactor.sql) que Postgres
--    nunca tuvo. Ya era un caso conocido -- ver el comentario en
--    worker/src/index.js junto a "Railway (que no tiene la columna
--    categorias_fijas en su esquema...)" -- pero sin la columna, un
--    redactor "sin equipo, con categoría(s) fija(s)" pierde esa
--    restricción en cuanto el sitio conmuta a Railway/Postgres: el
--    INSERT/UPDATE de usuarios ahí simplemente no la conoce, así que un
--    redactor de ese tipo creado o editado durante un failover perdería
--    la restricción de categoría sin ningún aviso.

BEGIN;

CREATE TABLE IF NOT EXISTS porras (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reader_id INTEGER NOT NULL REFERENCES readers(id) ON DELETE CASCADE,
  resultado_id INTEGER NOT NULL REFERENCES results(id) ON DELETE CASCADE,
  goles_local_predicho INTEGER NOT NULL,
  goles_visitante_predicho INTEGER NOT NULL,
  puntos_obtenidos INTEGER,
  resultado_acierto TEXT NOT NULL DEFAULT 'pendiente',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  UNIQUE (reader_id, resultado_id)
);

CREATE INDEX IF NOT EXISTS idx_porras_reader ON porras(reader_id);
CREATE INDEX IF NOT EXISTS idx_porras_resultado ON porras(resultado_id);

ALTER TABLE users ADD COLUMN IF NOT EXISTS categorias_fijas TEXT;

COMMIT;

-- ------------------------------------------------------------
-- Nota: "porras" ya se ha registrado en worker-secondary/sync/tables.mjs
-- (changeStrategy "updated_at", deleteDetection true por depender de dos
-- padres con ON DELETE CASCADE: readers y results), así que en cuanto
-- esta migración se aplique, sync/incremental.mjs empezará a replicar
-- sus filas desde D1 sin ningún paso manual adicional en el sync.
--
-- Sigue pendiente, fuera de este archivo SQL y del sync: si se quiere
-- que el failover a Railway sirva también /api/porras,
-- /api/porras/resumen y /api/porras/ranking (hoy no implementadas en
-- worker-secondary/src/index.js), portar esos tres endpoints desde
-- worker/src/index.js una vez esta tabla ya exista aquí.
-- ------------------------------------------------------------
