INSERT INTO equipo_alias_externo (nombre_externo, nombre_interno) VALUES
  ('Almería', 'UD Almería'),
  ('Tenerife', 'CD Tenerife'),
  ('Mallorca', 'RCD Mallorca'),
  ('Burgos', 'Burgos CF'),
  ('Las Palmas', 'UD Las Palmas'),
  ('Castellón', 'CD Castellón'),
  ('Girona', 'Girona FC'),
  ('Cádiz', 'Cádiz CF'),
  ('Granada', 'Granada CF'),
  ('Sabadell', 'CE Sabadell'),
  ('Sporting de Gijón', 'Real Sporting'),
  ('Córdoba', 'Córdoba CF'),
  ('Albacete', 'Albacete Balompié'),
  ('Eibar', 'SD Eibar'),
  ('Real Valladolid', 'Real Valladolid CF'),
  ('Eldense', 'CD Eldense'),
  ('Ceuta', 'AD Ceuta FC'),
  ('Leganés', 'CD Leganés');
